<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CustomCodeFramework.Core" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Postgres.EntityFramework" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Messaging" Version="0.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dhole.Reports.Application\Dhole.Reports.Application.csproj" />
    <ProjectReference Include="..\Dhole.Reports.Domain\Dhole.Reports.Domain.csproj" />
    <ProjectReference Include="..\Dhole.Reports.Contracts\Dhole.Reports.Contracts.csproj" />
  </ItemGroup>

</Project>
